services:
  storeapp:
    image: gogodze/store:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - DB_PATH=/data/db.db
    volumes:
      - ./db.db:/data/db.db