services:
  storeapp:
    image: gogodze/store-staging:latest
    restart: unless-stopped
    container_name: store
    env_file:
      - .env
    volumes:
      - ./db.db:/data/db.db
    networks:
      - app_net

networks:
  app_net:
    external: true
