services:
  storeapp:
    image: gogodze/store-staging:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./db.db:/data/db.db
    networks:
      - app_network

networks:
  app_network:
    external: true
