services:
  storeapp:
    image: gogodze/store:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./db.db:/data/db.db
    networks:
      - app_network

networks:
  app_network:
    external: true
